apiVersion: v1
kind: Service
metadata:
  name: vision-trainer
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: vision-trainer
  ports:
    - name: ddp
      port: {{ .Values.trainer.masterPort }}
      targetPort: {{ .Values.trainer.masterPort }}
