apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  name: vision-scale-bench-results
  annotations:
    crossplane.io/external-name: vision-scale-bench-results-ACCOUNT_ID
spec:
  deletionPolicy: Delete
  forProvider:
    region: eu-central-1
    tags:
      Project: vision-scale-bench
  providerConfigRef:
    name: default
