apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: aws-irsa
spec:
  serviceAccountTemplate:
    metadata:
      annotations:
        eks.amazonaws.com/role-arn: CROSSPLANE_ROLE_ARN
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-s3
spec:
  package: xpkg.crossplane.io/crossplane-contrib/provider-aws-s3:v1.21.1
  runtimeConfigRef:
    name: aws-irsa
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-ecr
spec:
  package: xpkg.crossplane.io/crossplane-contrib/provider-aws-ecr:v1.21.1
  runtimeConfigRef:
    name: aws-irsa
